name: Test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v13
      - uses: DeterminateSystems/magic-nix-cache-action@v8
      - name: configure CI timeouts
        run: |
          sed -i 's/timeoutMultiplier = 1/timeoutMultiplier = 3/' \
            tests/flake.nix
      - name: test
        run: |
          nix shell nixpkgs#gnome-shell \
                    nixpkgs#unzip \
                    -c bash -e MAINTENANCE.txt
